disabled_rules:
- inclusive_language
- trailing_whitespace
- switch_case_alignment
- block_based_kvo
- todo
- weak_delegate

opt_in_rules: 
- vertical_whitespace_between_cases

indentation: tabs

large_tuple:
  warning: 4
  error: 6

line_length: 
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true
  ignores_interpolated_strings: true
  warning: 160
  error: 180

identifier_name:
  allowed_symbols: "_"
  min_length: 1
  max_length: 
    warning: 90
    error: 1000
  excluded:
    - id
    - app

nesting:
  type_level: 3

type_name:
  allowed_symbols: "_"
  max_length: 
    warning: 80
    error: 90
  excluded:
    - app
    - T2
    - T6

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 10
  error: 15

cyclomatic_complexity:
  ignores_case_statements: true

file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true
